apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/Troy876/release-service/config/default?ref=f39e5d03eff5ff193531006ba34969e62ac47adc
images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/troytaylor/release-service
    newTag: test_oc_tag
namespace: release-service
